### ISSUE TITLE
CMake build from src doesn't get pointed to target pgkconfigdir for dependencies built from src

### ISSUE THREAD

**Issue by awalls-cx18** [gnuradio/pybombs#273]
When building a package from source (e.g. gr-fosphor), PyBOMBS (2.x) does not let CMake know about the ${prefix}/lib/pkgconfig directory, where pkg-config, used by CMake's FindPkgConfig module, can find package config files for dependencies PyBOMBS built from source (e.g. glfw3 for gr-phosphor).

In my particular case, the CMake build of gr-fosphor was (luckily?) finding the header file for the glfw3 built from source and installed under the ${prefix}, but the library found was the system's installed glfw2 library.  A snippet from CMakeCache.txt from a broken gr-fosphor build:

//Path to a file.
GLFW3_INCLUDE_DIRS:PATH=/home/andy/target/include     <--- Correct
//Path to a library.
GLFW3_LIBRARIES:FILEPATH=/usr/lib/libglfw.so   <---- Incorrect

The solution was to inform pkg-config about the target installation path in an environment variable before running PyBOMBS to build gr-fosphor:

PKG_CONFIG_PATH=${prefix}/lib/pkgconfig

which adds a path for pkg-config to search first, before all the default pkg-config paths.

It seems like PyBOMBS should be setting this automatically for at least CMake builds.
From the documentations, there was no obvious way, to me, to set the environment variable in the ~/.pybombs/config.yml file to have an env: resolve using the current ${prefix} in use.

**Comment by mbr0wn** [comment]
Good point -- I'm pondering if I should simply 'source' setup_env.sh before launching any process, like we're sourcing the environment file. That would set `PKG_CONFIG_PATH`.

A short term fix for you would be to amend your config.yml as such:

```{.yml}
[env]
  PKG_CONFIG_PATH: /path/to/prefix/lib/pkgconfig:$PKG_CONFIG_PATH
```

**Comment by mbr0wn** [comment]
...and you can use `$PYBOMBS_PREFIX` as an env variable.

**Comment by awalls-cx18** [comment]
Yeah.  Both of those workarounds seemed to break the PyBOMBS2 management of multiple builds stored under different prefixes though.

**Comment by mbr0wn** [comment]
You can edit the config.yml file inside the prefix's .pybombs dir.

**Comment by u0m3** [comment]
It is my impression that it ignores the `env` section or at least it does not export the vars properly.
I ran into this issue myself and my work-around was to export the env vars by hand.

My **~/.pybombs/config.yaml**
```yaml
--- 
categories: 
  common: 
    forcebuild: true
config: 
  cc: gcc
  cxx: g++
  default_prefix: default
  makewidth: "8"
  satisfy_order: "native,src"
env: 
  LD_LIBRARY_CONFIG: "~/gnuradio-env/lib:$LD_LIBRARY_CONFIG"
  LD_LIBRARY_PATH: "~/gnuradio-env/lib:$LD_LIBRARY_PATH"
  PATH: "~/gnuradio-env/bin:$PATH"
  PKG_CONFIG_PATH: "~/gnuradio-env/lib/pkgconfig:$PKG_CONFIG_PATH"
  PYTHONPATH: "~/gnuradio-env/lib/python2.7/dist-packages:$PYTHONPATH"
packages: 
  gnuradio: 
    forcebuild: true
    forceinstalled: false
  uhd:
    forcebuild: true
    forceinstalled: false
  gr-fcdproplus:
    forcebuild: true
    forceinstalled: false
prefix_aliases: 
  default: ~/gnuradio-env
recipes: 
  gr-etcetera: /home/rpopescu/.pybombs/recipes/gr-etcetera
  gr-recipes: /home/rpopescu/.pybombs/recipes/gr-recipes
```
